# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='内容')),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('create_date', models.DateTimeField(auto_now=True, null=True, verbose_name='生成时间')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True, null=True, verbose_name='生成时间')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Content', verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='标签名')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='父标签id')),
                ('queue', models.TextField(verbose_name='顺序')),
                ('grade', models.SmallIntegerField(blank=True, null=True, verbose_name='等级')),
                ('create_date', models.DateTimeField(auto_now=True, null=True, verbose_name='生成时间')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Label', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='content',
            name='labels',
            field=models.ManyToManyField(to='data.Label', verbose_name='标签'),
        ),
    ]
