# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-28 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='value',
            new_name='pid',
        ),
    ]
