# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20181028_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='标签名'),
        ),
    ]
