# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-29 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181029_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
    ]
