# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-29 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_content_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='attachment',
        ),
    ]
